import { JetBrains_Mono } from "next/font/google";
import "./globals.css";

//components
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import StairTransition from "@/components/StairTransition";
import Nav from "@/components/Nav";
import TopLeftImg from "@/components/TopLeftImg";
import Circles from "@/components/Circles";

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetbrainsMono",
});

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
  openGraph: {
    images: [
      {
        url: "/leocchi-new-logo.jpg",
        width: 500,
        height: 800,
        alt: "Logo for Portfolio",
      },
    ],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${jetbrainsMono.variable} page bg-site bg-cover flex flex-col min-h-screen`}>
        <Header />
        <StairTransition />

        <main className="flex-grow">
          <PageTransition>{children}</PageTransition>
        </main>

        <footer className="text-center text-white text-sm py-6 opacity-60">
          © {new Date().getFullYear()} Leo Louise E. Jimenez. All rights reserved.
        </footer>

        <TopLeftImg />
        <Circles />
      </body>
    </html>
  );
}
